repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=2048"]
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies: ["mdformat-gfm"]
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        additional_dependencies: ["stylelint", "stylelint-config-recommended"]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.10.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.6
    hooks:
      - id: prettier
        additional_dependencies:
          - "prettier"
          - "@prettier/plugin-php"
          - "@shufo/prettier-plugin-blade"
          - "prettier-plugin-tailwindcss"
        files: \.(html|js|jsx|ts|tsx|php|json|css|scss|md|yml|yaml)$
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.12.0
    hooks:
    - id: pretty-format-java
      args: [--autofix]
    - id: pretty-format-kotlin
      args: [--autofix]
    - id: pretty-format-yaml
      args: [--autofix, --indent, '2']
  - repo: https://github.com/jguttman94/pre-commit-gradle
    rev: v0.3.0
    hooks:
    - id: gradle-check
